---
- name: Converge
  hosts: all
  tasks:
    - name: Update APT cache
      apt:
        update_cache: true
        cache_valid_time: 3600
      when: ansible_os_family in ["Debian"]
    - name: Do it
      include_tasks: ../../tasks/main.yml